### ISSUE TITLE
cant install on ubuntu 14.04

### ISSUE THREAD

**Issue by shaharharap** [xivo-pbx/xivo-consul-packaging#1]
The following packages have unmet dependencies:
 consul : Depends: init-system-helpers (>= 1.18~) but 1.14 is to be installed

**Comment by sboily** [comment]
Hello, it doesn't working because we only package for debian, not ubuntu. I think the best for you, is forking the project and change the dependences.

**Comment by elessard1** [comment]
I updated the README so that it is a bit more obvious that the package in the xivo-dev distribution is only for Debian 8 (jessie). It might work on other platform, but we don't test it.
